/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalsHospitalIdRouteImport } from './routes/hospitals.$hospitalId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsHospitalIdRoute = HospitalsHospitalIdRouteImport.update({
  id: '/hospitals/$hospitalId',
  path: '/hospitals/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/ingestion': typeof IngestionRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/signup': typeof SignupRoute
  '/triage': typeof TriageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/ingestion': typeof IngestionRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/signup': typeof SignupRoute
  '/triage': typeof TriageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/ingestion': typeof IngestionRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/signup': typeof SignupRoute
  '/triage': typeof TriageRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/ingestion'
    | '/login'
    | '/map'
    | '/signup'
    | '/triage'
    | '/dashboard'
    | '/hospitals/$hospitalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/ingestion'
    | '/login'
    | '/map'
    | '/signup'
    | '/triage'
    | '/dashboard'
    | '/hospitals/$hospitalId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/contact'
    | '/ingestion'
    | '/login'
    | '/map'
    | '/signup'
    | '/triage'
    | '/_authenticated/dashboard'
    | '/hospitals/$hospitalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  IngestionRoute: typeof IngestionRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  SignupRoute: typeof SignupRoute
  TriageRoute: typeof TriageRoute
  HospitalsHospitalIdRoute: typeof HospitalsHospitalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$hospitalId': {
      id: '/hospitals/$hospitalId'
      path: '/hospitals/$hospitalId'
      fullPath: '/hospitals/$hospitalId'
      preLoaderRoute: typeof HospitalsHospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  IngestionRoute: IngestionRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  SignupRoute: SignupRoute,
  TriageRoute: TriageRoute,
  HospitalsHospitalIdRoute: HospitalsHospitalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
